let a = first.getAttribute("class")
console.log(a)
console.log(first.hasAttribute("class"))
console.log(first.hasAttribute("style"))
first.setAttribute("hidden","true")
first.removeAttribute("class")
console.log(first.dataset.game)
console.log(first.dataset.player)